name: 'Get top github contributions'
description: 'Create a comment for a PR on GitHub'
inputs:
  token:
    required: true  
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
outputs:
  top-contributions:
    description: 'Top contributions'
  notable-contributions:
    description: 'Notable contributions'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'